@extends('layouts.dashboard')

@section('title', $book->title . ' - Interlude')

@section('content')
<div class="container-fluid dashboard-container">
    @if (session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><p class="eyebrow mb-1">Book details</p><h2 class="mb-0">{{ $book->title }}</h2></div><div class="d-flex gap-2"><a href="{{ route('admin.books.edit', $book) }}" class="btn btn-primary"><i class="bi bi-pencil me-1"></i>Edit</a><a href="{{ route('admin.books.index') }}" class="btn btn-light">Kembali</a></div></div>
    <section class="dashboard-panel"><div class="row g-4"><div class="col-md-3"><img src="{{ $book->cover_image_url ?: 'https://via.placeholder.com/240x340?text=Book' }}" alt="{{ $book->title }}" class="img-fluid rounded shadow-sm"></div><div class="col-md-9"><div class="d-flex flex-wrap gap-2 mb-3">@if($book->is_new)<span class="badge text-bg-success">Baru</span>@endif @if($book->is_popular)<span class="badge text-bg-info">Populer</span>@endif @if($book->is_bestseller)<span class="badge text-bg-warning">Bestseller</span>@endif</div><dl class="row"><dt class="col-sm-3">Penulis</dt><dd class="col-sm-9">{{ $book->author }}</dd><dt class="col-sm-3">Kategori</dt><dd class="col-sm-9">{{ $book->category }}</dd><dt class="col-sm-3">Harga</dt><dd class="col-sm-9">Rp {{ number_format((float) $book->price, 0, ',', '.') }}</dd><dt class="col-sm-3">ISBN</dt><dd class="col-sm-9">{{ $book->isbn ?: '-' }}</dd><dt class="col-sm-3">Publikasi</dt><dd class="col-sm-9">{{ $book->published_at?->format('d M Y H:i') ?: '-' }}</dd></dl><hr><p>{{ $book->description ?: 'Tidak ada deskripsi.' }}</p><div class="row g-3 mt-3"><div class="col-sm-4"><small class="text-muted d-block">Views</small><strong>{{ number_format($book->view_count) }}</strong></div><div class="col-sm-4"><small class="text-muted d-block">Wishlist</small><strong>{{ number_format($book->wishlist_count) }}</strong></div><div class="col-sm-4"><small class="text-muted d-block">Sold</small><strong>{{ number_format($book->sold_count) }}</strong></div></div></div></div></section>
    <form method="POST" action="{{ route('admin.books.destroy', $book) }}" class="mt-3" onsubmit="return confirm('Hapus buku ini?')">@csrf @method('DELETE')<button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash me-1"></i>Hapus Buku</button></form>
</div>
@endsection
